volumes:
  kibana:
    driver: ${VOLUMES_DRIVER}

services:
### Kibana ###############################################
  kibana:
    build:
      context: ${KIBANA_HOST_PATH}
      args:
        - KIBANA_VERSION=${ELASTIC_STACK_VERSION}
    container_name: ${KIBANA_CONTAINER_NAME}
    hostname: ${KIBANA_HOSTNAME}
    privileged: true
    user: root
    ports:
      - "${KIBANA_HTTP_PORT}:5601"
    volumes:
      - ${ES_PATH}/certs:/usr/share/kibana/config/certs
      - ${DATA_HOST_PATH}/kibana:/usr/share/kibana/data # 需要777权限
    environment:
      - TZ=${TZ}
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://${ES_CONTAINER_NAME}:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - I18N_LOCALE="zh-CN"
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      backend:
        ipv4_address: ${KIBANA_BACKEND_IP}
    depends_on:
      es:
        condition: service_healthy
