volumes:
  pulsar-bookie1:
    driver: ${VOLUMES_DRIVER}

x-build: &build
  build:
    context: ${PULSAR_BOOKIE_HOST_PATH}
    args:
      PULSAR_VERSION: ${PULSAR_VERSION}

x-bookie-env: &bookie-env
  TZ: ${TZ}
  clusterName: ${PULSAR_CLUSTER_NAME}
  zkServers: "${PULSAR_ZOOKEEPER_CONTAINER_NAME}:2181"
  metadataServiceUri: "metadata-store:zk:${PULSAR_ZOOKEEPER_CONTAINER_NAME}:2181"
  BOOKIE_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m"

services:

### PULSAR BOOKIE ##############################################
  pulsar-bookie1:
    <<: *build
    container_name: ${PULSAR_BOOKIE_CONTAINER_NAME_NODE1}
    hostname: ${PULSAR_BOOKIE_HOSTNAME_NODE1}
    user: root
    privileged: true
    command: bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"
    volumes:
      - "${DATA_HOST_PATH}/${PULSAR_BOOKIE_CONTAINER_NAME_NODE1}:/pulsar/data/bookkeeper"
    environment:
      <<: *bookie-env
      # otherwise every time we run docker compose uo or down we fail to start due to Cookie
      # See: https://github.com/apache/bookkeeper/blob/405e72acf42bb1104296447ea8840d805094c787/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Cookie.java#L57-68
      advertisedAddress: ${PULSAR_BOOKIE_CONTAINER_NAME_NODE1}
    networks:
      backend:
        ipv4_address: ${PULSAR_BOOKIE_BACKEND_IP_NODE1}
    depends_on:
      pulsar-zookeeper:
        condition: service_healthy
      pulsar-init:
        condition: service_completed_successfully
