version: "3.8"

include:
  - ../_common/docker-compose-common.yml
  - ./docker-compose-busybox.yml
  - ./docker-compose-portainer.yml
  - ./docker-compose-mysql57.yml
  - ./docker-compose-mysql.yml
  - ./docker-compose-redis.yml
  - ./docker-compose-redis-stack.yml
  - ./docker-compose-memcached.yml
  # - ./docker-compose-docker-in-docker.yml
  - ./docker-compose-postgres.yml
  - ./docker-compose-pgadmin.yml
  - ./docker-compose-certbot.yml
  - ./docker-compose-phpmyadmin.yml
  - ./docker-compose-tomcat8.yml
  - ./docker-compose-mongo.yml
  - ./docker-compose-rabbitmq.yml
  - ./docker-compose-soketi.yml
  - ./docker-compose-caddy.yml
  - ./docker-compose-postgres-postgis.yml
  - ./docker-compose-beanstalkd.yml
  - ./docker-compose-beanstalk_console.yml

























### Grafana ##############################################
### MongoWebUI ###########################################
### JupyterHub ###########################################
### OpenResty Server #####################################
### Metabase #############################################
### SONARQUBE ############################################
### kafka ################################################
### kafka-manager ########################################
### keycloak #############################################
### tarantool ###########################################