version: '3.8'

volumes:
  mongo:
    driver: ${VOLUMES_DRIVER}

services:

### MongoDB ##############################################
  mongo:
    build:
      context: ${MONGO_HOST_PATH}
      args:
        - MONGO_VERSION=${MONGO_VERSION}
    container_name: ${MONGO_CONTAINER_NAME}
    hostname: ${MONGO_HOSTNAME}
    privileged: true
    ports:
      - "${MONGO_HOST_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mongo/db:/data/db
      - ${DATA_PATH_HOST}/mongo/configdb:/data/configdb
    networks:
      frontend:
        ipv4_address: ${MONGO_FRONTEND_IP}
      backend:
        ipv4_address: ${MONGO_BACKEND_IP}