volumes:
  memcached1:
    driver: ${VOLUMES_DRIVER}
  memcached2:
    driver: ${VOLUMES_DRIVER}
  memcached3:
    driver: ${VOLUMES_DRIVER}

x-env: &env
  TZ: ${TZ}

x-build: &build
  build:
    context: ${MEMCACHED_HOST_PATH}
    args:
      MEMCACHED_VERSION: ${MEMCACHED_VERSION}

services:
### MEMCACHED NODE1 ##############################################
  memcached1:
    <<: *build
    hostname: ${MEMCACHED_HOSTNAME_NODE1}
    container_name: ${MEMCACHED_CONTAINER_NAME_NODE1}
    privileged: true
    ports:
      - "${MEMCACHED_HOST_PORT_NODE1}:11211"
    environment:
      <<: *env
    volumes:
     - ${DATA_HOST_PATH}/${MEMCACHED_CONTAINER_NAME_NODE1}/data:/var/lib/memcached
    networks:
      backend:
        ipv4_address: ${MEMCACHED_BACKEND_IP_NODE1}

### MEMCACHED NODE2 ##############################################
  memcached2:
    <<: *build
    hostname: ${MEMCACHED_HOSTNAME_NODE2}
    container_name: ${MEMCACHED_CONTAINER_NAME_NODE2}
    privileged: true
    ports:
      - "${MEMCACHED_HOST_PORT_NODE2}:11211"
    environment:
      <<: *env
    volumes:
     - ${DATA_HOST_PATH}/${MEMCACHED_CONTAINER_NAME_NODE2}/data:/var/lib/memcached
    networks:
      backend:
        ipv4_address: ${MEMCACHED_BACKEND_IP_NODE2}

### MEMCACHED NODE3 ##############################################
  memcached3:
    <<: *build
    hostname: ${MEMCACHED_HOSTNAME_NODE3}
    container_name: ${MEMCACHED_CONTAINER_NAME_NODE3}
    privileged: true
    ports:
      - "${MEMCACHED_HOST_PORT_NODE3}:11211"
    environment:
      <<: *env
    volumes:
     - ${DATA_HOST_PATH}/${MEMCACHED_CONTAINER_NAME_NODE3}/data:/var/lib/memcached
    networks:
      backend:
        ipv4_address: ${MEMCACHED_BACKEND_IP_NODE3}
