volumes:
  xxjob-mysql:
    driver: ${VOLUMES_DRIVER}

services:

### Mysql ################################################
  xxjob-mysql:
    build:
      context: ${MYSQL_HOST_PATH}
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    hostname: ${MYSQL_HOSTNAME}
    container_name: ${MYSQL_CONTAINER_NAME}
    privileged: true
    user: root
    volumes:
      - ${DATA_HOST_PATH}/${MYSQL_CONTAINER_NAME}:/var/lib/mysql # 需要777权限
      - ${LOG_HOST_PATH}/${MYSQL_CONTAINER_NAME}:/var/log
      - ${MYSQL_HOST_PATH}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      TZ: "${TZ}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      backend:
        ipv4_address: ${MYSQL_BACKEND_IP}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
