volumes:
  postgres:
    driver: ${VOLUMES_DRIVER}

services:

### PostgreSQL ###########################################
  postgres:
    build:
      context: ${POSTGRES_HOST_PATH}
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    hostname: ${POSTGRES_HOSTNAME}
    privileged: true
    user: root
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # jupyterhub
      JUPYTERHUB_POSTGRES_INIT: ${JUPYTERHUB_POSTGRES_INIT}
      JUPYTERHUB_POSTGRES_USER: ${JUPYTERHUB_POSTGRES_USER}
      JUPYTERHUB_POSTGRES_PASSWORD: ${JUPYTERHUB_POSTGRES_PASSWORD}
      JUPYTERHUB_POSTGRES_DB: ${JUPYTERHUB_POSTGRES_DB}
    volumes:
      - ${DATA_HOST_PATH}/${POSTGRES_CONTAINER_NAME}:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      backend:
        ipv4_address: ${POSTGRES_BACKEND_IP}
    healthcheck:
      test: [ "CMD", "pg_isready" ,"-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
