volumes:
  minio1:
    driver: ${VOLUMES_DRIVER}
  minio2:
    driver: ${VOLUMES_DRIVER}
  minio3:
    driver: ${VOLUMES_DRIVER}
  minio4:
    driver: ${VOLUMES_DRIVER}

x-env: &env
  TZ: ${TZ}
  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

x-healthcheck: &healthcheck
    test: ["CMD", "curl", "-f", "http://localhost:${MINIO_CONSOLE_PORT_CONTAINER}/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

x-build: &build
  build:
    context: ${MINIO_HOST_PATH}
    args:
      MINIO_VERSION: ${MINIO_VERSION}

x-command: &command "server --console-address ':${MINIO_CONSOLE_PORT_CONTAINER}' http://${MINIO_CONTAINER_NAME_PREFIX}{1...4}/${MINIO_DATA_DIR_NAME_PREFIX}{1...2}"

x-labels: &labels
  - "traefik.enable=true"
  - "traefik.http.routers.minio.entrypoints=${TRAEFIK_ENTRYPOINTS_MINIO_API}"
  - "traefik.http.routers.minio.rule=Host(`localhost`)"
  - "traefik.http.services.minio.loadbalancer.server.port=${MINIO_CONSOLE_PORT_CONTAINER}"
  - "traefik.http.services.minio.loadbalancer.server.scheme=http"
  - "traefik.http.services.minio.loadbalancer.passhostheader=true"

x-extra_hosts: &extra_hosts
  - "${MINIO_HOSTNAME_NODE1}:${MINIO_BACKEND_IP_NODE1}"
  - "${MINIO_HOSTNAME_NODE2}:${MINIO_BACKEND_IP_NODE2}"
  - "${MINIO_HOSTNAME_NODE3}:${MINIO_BACKEND_IP_NODE3}"
  - "${MINIO_HOSTNAME_NODE4}:${MINIO_BACKEND_IP_NODE4}"

services:
### MINIO NODE1 ##############################################
  minio1:
    <<: *build
    container_name: ${MINIO_CONTAINER_NAME_NODE1}
    hostname: ${MINIO_HOSTNAME_NODE1}
    command: *command
    labels: *labels
    extra_hosts: *extra_hosts
    privileged: true
    ports:
      - "${MINIO_CONSOLE_HOST_PORT_NODE1}:${MINIO_CONSOLE_PORT_CONTAINER}"
    volumes:
      - ${DATA_HOST_PATH}/${MINIO_CONTAINER_NAME_NODE1}/${MINIO_DATA_DIR_NAME_PREFIX}1:/${MINIO_DATA_DIR_NAME_PREFIX}1
      - ${DATA_HOST_PATH}/${MINIO_CONTAINER_NAME_NODE1}/${MINIO_DATA_DIR_NAME_PREFIX}2:/${MINIO_DATA_DIR_NAME_PREFIX}2
    environment:
      <<: *env
    healthcheck:
      <<: *healthcheck
    networks:
      backend:
        ipv4_address: ${MINIO_BACKEND_IP_NODE1}

### MINIO NODE2 ##############################################
  minio2:
    <<: *build
    container_name: ${MINIO_CONTAINER_NAME_NODE2}
    hostname: ${MINIO_HOSTNAME_NODE2}
    command: *command
    extra_hosts: *extra_hosts
    privileged: true
    ports:
      - "${MINIO_CONSOLE_HOST_PORT_NODE2}:${MINIO_CONSOLE_PORT_CONTAINER}"
    volumes:
      - ${DATA_HOST_PATH}/${MINIO_CONTAINER_NAME_NODE2}/${MINIO_DATA_DIR_NAME_PREFIX}1:/${MINIO_DATA_DIR_NAME_PREFIX}1
      - ${DATA_HOST_PATH}/${MINIO_CONTAINER_NAME_NODE2}/${MINIO_DATA_DIR_NAME_PREFIX}2:/${MINIO_DATA_DIR_NAME_PREFIX}2
    environment:
      <<: *env
    healthcheck:
      <<: *healthcheck
    networks:
      backend:
        ipv4_address: ${MINIO_BACKEND_IP_NODE2}

### MINIO NODE3 ##############################################
  minio3:
    <<: *build
    container_name: ${MINIO_CONTAINER_NAME_NODE3}
    hostname: ${MINIO_HOSTNAME_NODE3}
    command: *command
    extra_hosts: *extra_hosts
    privileged: true
    ports:
      - "${MINIO_CONSOLE_HOST_PORT_NODE3}:${MINIO_CONSOLE_PORT_CONTAINER}"
    volumes:
      - ${DATA_HOST_PATH}/${MINIO_CONTAINER_NAME_NODE3}/${MINIO_DATA_DIR_NAME_PREFIX}1:/${MINIO_DATA_DIR_NAME_PREFIX}1
      - ${DATA_HOST_PATH}/${MINIO_CONTAINER_NAME_NODE3}/${MINIO_DATA_DIR_NAME_PREFIX}2:/${MINIO_DATA_DIR_NAME_PREFIX}2
    environment:
      <<: *env
    healthcheck:
      <<: *healthcheck
    networks:
      backend:
        ipv4_address: ${MINIO_BACKEND_IP_NODE3}

### MINIO NODE4 ##############################################
  minio4:
    <<: *build
    container_name: ${MINIO_CONTAINER_NAME_NODE4}
    hostname: ${MINIO_HOSTNAME_NODE4}
    command: *command
    extra_hosts: *extra_hosts
    privileged: true
    ports:
      - "${MINIO_CONSOLE_HOST_PORT_NODE4}:${MINIO_CONSOLE_PORT_CONTAINER}"
    volumes:
      - ${DATA_HOST_PATH}/${MINIO_CONTAINER_NAME_NODE4}/${MINIO_DATA_DIR_NAME_PREFIX}1:/${MINIO_DATA_DIR_NAME_PREFIX}1
      - ${DATA_HOST_PATH}/${MINIO_CONTAINER_NAME_NODE4}/${MINIO_DATA_DIR_NAME_PREFIX}2:/${MINIO_DATA_DIR_NAME_PREFIX}2
    environment:
      <<: *env
    healthcheck:
      <<: *healthcheck
    networks:
      backend:
        ipv4_address: ${MINIO_BACKEND_IP_NODE4}
