include:
  - ../../_common/docker-compose-common.yml
  - ./docker-compose-application.yml
  - ./docker-compose-gitlab.yml
  - ./docker-compose-jenkins.yml
  - ./docker-compose-postgres.yml
  - ./docker-compose-redis.yml
  # - ./docker-compose-docker-in-docker.yml
  # - ./docker-compose-gitlab-runner.yml