volumes:
  spider-mongo:
    driver: ${VOLUMES_DRIVER}

services:

### MongoDB ##############################################
  spider-mongo:
    build:
      context: ${MONGO_HOST_PATH}
      args:
        - MONGO_VERSION=${MONGO_VERSION}
    container_name: ${MONGO_CONTAINER_NAME}
    hostname: ${MONGO_HOSTNAME}
    privileged: true
    ports:
      - "${MONGO_HOST_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ${DATA_HOST_PATH}/mongo/db:/data/db
      - ${DATA_HOST_PATH}/mongo/configdb:/data/configdb
    networks:
      backend:
        ipv4_address: ${MONGO_BACKEND_IP}
