volumes:
  dc-redis:
    driver: ${VOLUMES_DRIVER}

services:

### Redis ##############################################
  dc-redis:
    build:
      context: ${REDIS_STACK_HOST_PATH}
      args:
        - REDIS_STACK_VERSION=${REDIS_STACK_VERSION}
    hostname: ${REDIS_STACK_HOSTNAME}
    container_name: ${REDIS_STACK_CONTAINER_NAME}
    privileged: true
    user: root
    volumes:
      - ${DATA_HOST_PATH}/redis:/data
      - ${LOG_HOST_PATH}/redis:/var/log/redis
    ports:
      - "${REDIS_STACK_HOST_PORT}:6379"
      - "${REDIS_STACK_INSIGHT_PORT}:8001"
    environment:
      - "TZ=${TZ}"
      - "REDIS_ARGS=--requirepass ${REDIS_STACK_PASSWORD} --appendonly yes"
    networks:
      backend:
        ipv4_address: ${REDIS_STACK_BACKEND_IP}
